spring:
  application:
    name: cosmosdb
#  autoconfigure:
#    exclude: com.azure.spring.cloud.autoconfigure.implementation.context.AzureTokenCredentialAutoConfiguration

azure:
  cosmos:
    uri: ${COSMOS_URI}
    key: ${COSMOS_KEY}
    database: ${COSMOS_DB}
    #consistency-level: Session

server:
  port: 8090

logging:
  level:
    root: INFO
#    com.azure.cosmos: DEBUG
#    org.springframework.data.cosmos: DEBUG
