spring:
  application:
    name: cosmosdb
#  autoconfigure:
#    exclude: com.azure.spring.cloud.autoconfigure.implementation.context.AzureTokenCredentialAutoConfiguration
  data:
    cosmos:
      uri: https://localhost:8081
      key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
      database: cosmosdb
#      consistency-level: Session

server:
  port: 8090

logging:
  level:
    com.azure.cosmos: DEBUG
    org.springframework.data.cosmos: DEBUG
